### ISSUE TITLE
Release of the code

### ISSUE THREAD

**Issue by zhengyu-su** [TtuHamg/DriveDiTFit#1]
Hi, thanks for the great work! I wanted to ask when are you planning to release the code? Are you also going to release the code for the downstream evaluation?

**Comment by TtuHamg** [comment]
Thank you so much for your interest in our work! Due to the submission of other work, our code has been delayed slightly. However, we are in the process of organizing the code and plan to release it as open source very soon.

Regarding the downstream evaluation, we have drawn on approaches from [Yolov8](https://github.com/ultralytics/ultralytics). For our evaluation, we have augmented an existing dataset with driving data generated under various weather and lighting conditions. We then train visual models with this enriched dataset and assess their performance specifically under challenging weather and nighttime conditions.

**Comment by zhengyu-su** [comment]
Thanks for your reply! Another question that confuses me is how do you train the DiT model actually with the driving datasets? Do you modify the final output layer? Or just select some mapping and only fine-tune these classes?
